### ISSUE TITLE
Add Debian RISC-V

### ISSUE THREAD

**Issue by benz0li** [utmapp/mac.getutm.app#31]
RISC-V is now an official Debian architecture: https://lists.debian.org/debian-riscv/2023/07/msg00053.html

The prebuilt is available at https://dl.b-data.ch/utm/debian-unstable-riscv64-utm4.zip

*_virtual_machines/debian-riscv64.md*:

```
---
title: Debian RISC-V
architecture: RISC-V64
memory: 1024 MiB
disk: 10 GiB
display: Console
spice_installed: false
username: debian
password: debian
screenshot: to be defined
download: to be defined
utm_link: true
---
## Notes
* Root account username/password is `root`/`password`. You should change this.
* This is a Debian image generated by the [Debian Quick Image Baker](https://people.debian.org/~gio/dqib/).
* Suite: unstable; APT source: `deb [arch=riscv64] http://deb.debian.org/debian/ unstable main`.
```

**Comment by benz0li** [comment]
> so that would be another reason to create a newer image.

@rxhfcy Done.

[debian-unstable-riscv64-utm4.zip](https://dl.b-data.ch/utm/debian-unstable-riscv64-utm4.zip) now contains the image from the [pipeline](https://gitlab.com/giomasce/dqib/-/pipelines) run on 26 November 2023 at 09:27:10 CET.

**Comment by ksbjr** [comment]
Please fix networking .

**Comment by benz0li** [comment]
> Please fix networking .

What do you mean by that?

**Comment by benz0li** [comment]
> Everything used to work fine before, no idea what changed.

Sometimes I encounter network problems, too. The only thing that helps is rebooting the machine.

**Comment by ksbjr** [comment]
Please remake img and test networking it seems  to not work at all . I changed to a bridged network where it should get a ip right from my router and watching a net trace it does not even attemp to do anything to get a ip from the router meaning things are missing.

**Comment by ksbjr** [comment]
ok found the fix. you have to download the newer img here [new img](https://people.debian.org/~gio/dqib/) rename file to .zip and then unpack it. go into utm and on the riscv vm delete the virtual driv. and then add a new vitrual drive and select the qcow2 img.  Next you have to change networking in the vm to bridged, boot the img and login root/root and edit /etc/network/interface file and change the ip to match your network. seems dhcp is not in these images. once you do this reboot. then relogin and dpkg-reconfigure tzdata and set your time zone. then use date to set your time. then you can apt update.

**Comment by benz0li** [comment]
> BTW if it's not a huge hassle, could you create a newer image once again?

Done. 

---

The network configuration remains unchanged for my images, i.e.

* Network Mode: Emulated VLAN
* Emulated Network Card: virtio-net-pci

**Comment by TimTheBig** [comment]
> Next you have to change networking in the vm to bridged, boot the img and login root/root and edit /etc/network/interface file and **change the ip to match your network**. seems dhcp is not in these images.

What do you mean by "change the ip to match your network"

**Comment by N4CNR** [comment]
what is the defualt login ?

**Comment by benz0li** [comment]
> what is the defualt login ?

See https://github.com/utmapp/mac.getutm.app/issues/31#issue-1821642308

**Comment by rxhfcy** [comment]
@benz0li
Would you consider updating the image again, and switching it to Debian 13 (trixie)? Trixie feels far less intimidating than "unstable".

I believe trixie [will have RISC-V support](https://www.phoronix.com/news/Debian-Installer-Trixie-Alpha-1) and is set to become the [new official stable](https://release.debian.org/) release pretty soon, hopefully around mid-year.

P.S. UTM 4.6.x seems to have fixed the previous networking problems. I don't think there was anything wrong with your image (possibly a QEMU issue)?
